fix: Align right header element correctly
artsy/palette-mobile pull request #200
Opened 2024-03-04 12:19 UTC by olerichter00

### Description

Align right header element correctly.

2024-03-04 15:56 UTC, damassi commented on src/elements/Skeleton/Skeleton.tsx
> +      <Text {...rest} bg={color("black10")} color={color("rgba(0, 0, 0, 0)")}>
This breaks darkmode

2024-03-04 15:59 UTC, damassi requested changes
I have a sneaking suspicion that this change might break Folio, which has a different manner of of title behavior than eigen (mostly left aligned, up to the width of the left element). Can we achieve the same thing by remaining with flexbox? As soon as things become manually positioned we lose all manner of flexibility. 

Also, not sure i'm seeing the issue in the screenshots.

2024-03-04 16:00 UTC, MounirDhahri approved these changes
LGTM, I am sure you already did it, but I would only suggest to test this in different screens because it's being used not only in Eigen screens but also in Folio

2024-03-04 16:00 UTC, MounirDhahri commented on src/elements/Screen/Header.tsx
> +      <Flex position="absolute" left={0} flexDirection="row" minWidth={screenWidth}>
did position `absolute` with a defined `width` not work here?

2024-03-04 16:02 UTC, olerichter00 commented on src/elements/Skeleton/Skeleton.tsx
> +      <Text {...rest} bg={color("black10")} color={color("rgba(0, 0, 0, 0)")}>
Thanks! This change isn't releated to the fix, forgot to remove it before pushing my changes 🙄

2024-03-04 16:19 UTC, olerichter00 commented
> I have a sneaking suspicion that this change might break Folio, which has a different manner of of title behavior than eigen (mostly left aligned, up to the width of the left element). Can we achieve the same thing by remaining with flexbox? As soon as things become manually positioned we lose all manner of flexibility.
Also, not sure i'm seeing the issue in the screenshots.

Thanks for the reviews 🙏 

Before this fix, we had to set the width of the right element manually to ensure it is rendered correctly ([Eigen code](https://github.com/artsy/eigen/blob/adada5761a116f314f21a0ce60453c616fd285a4/src/app/Scenes/Activity/components/PartnerOfferCreatedNotification.tsx#L46)).

I just realized that what I'm trying to achieve with `position: absolute` would also work by setting `flex: 1` for both the left and right elements to ensure they have the same size, positioning the title exactly in the center of the screen ([JSFiddle with CSS example](https://jsfiddle.net/olerichter00/7ru59kzo/))💡 I'll update this PR and get rid of the `position: absolute`.

2024-03-04 17:46 UTC, damassi commented
Sweet, that seems like a good fix!

2024-03-05 14:21 UTC, olerichter00 commented
Closing this PR in favor of https://github.com/artsy/palette-mobile/pull/203

2024-03-05 14:21 UTC, closed without merging